lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - assets/nf-core-taxmarker_logo_light.png
    - docs/images/nf-core-taxmarker_logo_light.png
    - docs/images/nf-core-taxmarker_logo_dark.png
  nextflow_config:
    - params.input
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Daniel Lundin
  description: This pipeline checks sequences for their phylogenetic signal against
    their taxonomy
  force: false
  is_nfcore: true
  name: taxmarker
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - gpu
  version: 1.0.0dev
